name: Steam Hour Booster - Scheduler

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  boost_hours:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Exportar variables de entorno
        run: |
          echo "games=${{ secrets.STEAM_GAMES }}" >> $GITHUB_ENV
          echo "accounts=${{ secrets.STEAM_ACCOUNTS }}" >> $GITHUB_ENV

      - name: Ejecutar Steam Booster
        run: node index.js
